### ISSUE TITLE
Corrupt BLittle Image

### ISSUE THREAD

**Issue by hbomb79** [viluon/Zombease#1]
Not sure if this is already known to you, apologies if this is the case.

The Zombease title seen after running `menu.lua` is not how it appears in your forum screenshots, leading me to believe you are not experiencing the same issue.

Here is how it appears on my end ![](http://puu.sh/sV6VY/50e8881862.png)

**Comment by viluon** [comment]
Whoa! That is rather odd. It looks like something went wrong with either your platform or that file. Let me do a smoke test for the cause. Meanwhile, what platform is this on?

**Comment by hbomb79** [comment]
I am running CCEmuRedux

![](http://puu.sh/sV7iw/2d030cb5b3.png)

**Comment by viluon** [comment]
https://github.com/viluon/Zombease/commit/283188650985cfa03f2a758908ee51b9fa3377f2 switched to base64 encoding for the relevant binary files (currently the only one being actually loaded is the logo). It would be very helpful if you could download the latest version (just run `pastebin run SNnkfxnx` again, it respects existing saves) and report on whether this commit fixed the situation.

**Comment by hbomb79** [comment]
Re-installing using the command provided did indeed fix the problem. Thank you.

**Comment by viluon** [comment]
Awesome, thanks a lot for your report @hbomb79!
